name: Dayone
title: Dayone blog
description: This is the personal blog based on Jekflix. Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - blog
  - AI
  - computer science
  - Essay
  - 칼럼
show_hero: True
menu:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About
    url: /about
  - title: Contact
    url: /contact
  # - title: Feed
  #   url: /feed.xml
email: dayone.tech.official@gmail.com
# See: https://disqus.com/
disqus_username: dayonetechofficial
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xwkyqzvw
paginate: 12